### ISSUE TITLE
Can't generate tones above ~14.5kHz

### ISSUE THREAD

**Issue by caleb-allen** [benmoran56/chippy#3]
Hello! Me again. I seem to be running into issues generating any waves above ~14.5kHz, I've tried on multiple machines. My hearing range goes to about 16kHz, so I don't believe it's my perception. I also used a frequency detector which shows 16kHz when using a generator such as [this](http://onlinetonegenerator.com/) (I can also hear the tones from the generator) but not with chippy. The issue can be recreated with this code:

```
import chippy
synth = chippy.Synthesizer()
synth.save_wave(synth.sine_pcm(frequency=16000))
```

although with 

`synth.save_wave(synth.sine_pcm(frequency=14500))`

it seems to work. Anything above that seems to have some troubles. The issue appears to be present for all waveforms.

Thanks in advance

**Comment by benmoran56** [comment]
Hi Caleb, this is an issue with precision. You can produce audible tones by bumping up the sample framerate to 96k. (The default framerate is 44100) .
```
import chippy
synth = chippy.Synthesizer(framerate=96000)
synth.save_wave(synth.sine_pcm(frequency=16000))
```
Internally, the wave data is just standard floats. There isn't enough precision currently for such high frequencies. I didn't really bother to test these high frequency cases, since notes in the musical scales are OK with float precision.

Let me know if upping the framerate will work out for you or not.
